### ISSUE TITLE
Release 1.0.2 of the backend KO

### ISSUE THREAD

**Issue by mtoma** [dotse/zonemaster-backend#103] opened 2015-05-19 05:01 UTC
The release 1.0.2 of the zonemaster backend doesn't work. It works for a few hours than simply dies.
Often it is not even possible to start the zm_wb_daemon script at all.
A rollback was required.

Here are the traces:
perl -I ./lib/ script/zm_wb_daemon start
zonemaster-webbackend-daemon                                  [Started]
[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ DBD::Pg::db selectrow_array failed: no statement executing at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 63.
DBD::Pg::db selectrow_array failed: no statement executing at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 63.
le message de type 0x49 est arrivé alors que le serveur était en attente
le message de type 0x5a est arrivé alors que le serveur était en attente
Use of uninitialized value in subroutine entry at /home/afnicreg/perl5/perlbrew/perls/perl-5.20.1/lib/5.20.1/x86_64-linux-thread-multi/Encode.pm line 203.
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 126.
le message de type 0x49 est arrivé alors que le serveur était en attente
le message de type 0x5a est arrivé alors que le serveur était en attente
DBD::Pg::db do warning:  at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 61.
DBD::Pg::db selectrow_array failed: no statement executing at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 63.
DBD::Pg::db selectrow_array failed: no statement executing at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 63.
DBD::Pg::db do warning:  at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 160.
DBD::Pg::dr connect_cached warning:  at /home/afnicreg/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux-thread-multi/DBI.pm line 681.
DBD::Pg::dr connect_cached warning:  at /home/afnicreg/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux-thread-multi/DBI.pm line 681.
Use of uninitialized value in subroutine entry at /home/afnicreg/perl5/perlbrew/perls/perl-5.20.1/lib/5.20.1/x86_64-linux-thread-multi/Encode.pm line 203.
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 126.

[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ curl -H "Content-Type: application/json"   -d '{"params":"","jsonrpc":"2.0","id":140715758026879,"method":"version_info"}'  http://localhost:5000/
{"result":"Zonemaster Test Engine Version: v1.0.1","jsonrpc":"2.0","id":140715758026879}[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ curl -H "Content-Type: application/json"   -d '{"params":"","jsonrpc":"2.0","id":140715758026879,"method":"version_info"}'  http://localhost:5000/                                     perl -I ./lib/ script/zm_wb_daemon status
zonemaster-webbackend-daemon                                  [Running]
[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ perl -I ./lib/ script/zm_wb_daemon status
zonemaster-webbackend-daemon                                  [Running]
[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ perl -I ./lib/ script/zm_wb_daemon status
zonemaster-webbackend-daemon                                  [Running]
[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ perl -I ./lib/ script/zm_wb_daemon status
zonemaster-webbackend-daemon                                  [Running]
[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ perl -I ./lib/ script/zm_wb_daemon status
zonemaster-webbackend-daemon                                  [Running]
[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ perl -I ./lib/ script/zm_wb_daemon status
zonemaster-webbackend-daemon                                  [Running]
[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ perl -I ./lib/ script/zm_wb_daemon status
zonemaster-webbackend-daemon                                  [Running]
[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ perl -I ./lib/ script/zm_wb_daemon status
zonemaster-webbackend-daemon                                  [Running]
[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ perl -I ./lib/ script/zm_wb_daemon status
zonemaster-webbackend-daemon                                  [Running]
[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ perl -I ./lib/ script/zm_wb_daemon status
zonemaster-webbackend-daemon                                  [Running]
[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ perl -I ./lib/ script/zm_wb_daemon status
zonemaster-webbackend-daemon                                  [Running]
[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ perl -I ./lib/ script/zm_wb_daemon status
zonemaster-webbackend-daemon                                  [Running]
[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ perl -I ./lib/ script/zm_wb_daemon status
zonemaster-webbackend-daemon                                  [Running]
[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ perl -I ./lib/ script/zm_wb_daemon status
zonemaster-webbackend-daemon                                  [Running]
[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ perl -I ./lib/ script/zm_wb_daemon status
zonemaster-webbackend-daemon                                  [Running]
[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ perl -I ./lib/ script/zm_wb_daemon status
zonemaster-webbackend-daemon                                  [Running]
[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ DBD::Pg::db do warning:  at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 61.
DBD::Pg::db selectrow_array failed: no statement executing at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 63.
Use of uninitialized value in subroutine entry at /home/afnicreg/perl5/perlbrew/perls/perl-5.20.1/lib/5.20.1/x86_64-linux-thread-multi/Encode.pm line 203.
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 126.

[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ perl -I ./lib/ script/zm_wb_daemon status
zonemaster-webbackend-daemon                                  [Running]
[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ DBD::Pg::db do warning:  at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 61.
DBD::Pg::db selectrow_array failed: no statement executing at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 63.
DBD::Pg::db selectrow_array warning:  at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 158.
DBD::Pg::db selectrow_array warning:  at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 158.
DBD::Pg::db selectrow_array failed: no statement executing at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 63.
DBD::Pg::db do warning:  at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 61.
DBD::Pg::db selectrow_array failed: no statement executing at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 63.
Use of uninitialized value in subroutine entry at /home/afnicreg/perl5/perlbrew/perls/perl-5.20.1/lib/5.20.1/x86_64-linux-thread-multi/Encode.pm line 203.
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 126.
DBD::Pg::db selectrow_array warning:  at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 63.
DBD::Pg::dr connect_cached warning:  at /home/afnicreg/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux-thread-multi/DBI.pm line 681.
DBD::Pg::db selectrow_array warning:  at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 63.
Use of uninitialized value in subroutine entry at /home/afnicreg/perl5/perlbrew/perls/perl-5.20.1/lib/5.20.1/x86_64-linux-thread-multi/Encode.pm line 203.
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 126.
DBD::Pg::dr connect_cached warning:  at /home/afnicreg/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux-thread-multi/DBI.pm line 681.
DBD::Pg::db do warning:  at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 61.
DBD::Pg::db selectrow_array failed: no statement executing at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 63.
DBD::Pg::db do warning:  at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 61.
DBD::Pg::db selectrow_array warning:  at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 63.
DBD::Pg::dr connect_cached warning:  at /home/afnicreg/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux-thread-multi/DBI.pm line 681.
DBD::Pg::db selectrow_array failed:  at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 63.
DBD::Pg::db selectrow_array failed: no statement executing at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 158.
DBD::Pg::db selectrow_array failed: no statement executing at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 158.
DBD::Pg::db do failed:  at lib/Zonemaster/WebBackend/DB/PostgreSQL.pm line 61.

[afnicreg@zonemaster.rd.nic.fr zonemaster-backend]$ perl -I ./lib/ script/zm_wb_daemon status
zonemaster-webbackend-daemon                              [Not Running]

**Comment by mtoma** [comment] 2015-05-19 05:07
Rolled back at release 584594c985d3190b35da7e975994fceb6ed4b2c8 from March 11 2015

**Comment by pawal** [comment] 2015-05-19 08:23
Are you looking into this issue?

**Comment by mtoma** [comment] 2015-05-19 11:02
As far as I'm concerned no.
I just did a rollback to the newest possible version.
I just did a very quick look on a few newsgroups the last night to decide I had to rollback the release because it seems the observed problem is not a simplistic one.

----- Original Message -----

**Comment by pahi** [comment] 2015-05-19 14:22
Thank you for making sure that the service is reachable. However, this issue still needs to be solved.

**Comment by mtoma** [comment] 2015-05-20 10:57
I agree Patrik,

I just need to know who and when is supposed to fix this problem.
I have my idea on it and can work on it but I need a confirmation from Sandoche that this issue is higher priority than everything else.

I'd like to fix this issue at the same time as the setup of the continuous integration environment (at least some kind of it) as it seems to me very clear that the main problem we need to address urgently is a pre-release testing release to make sure that both the PostgeSQL based backend and the MySQL based backend are really working before releasing to the production server.

Michal

----- Original Message -----

**Comment by sandoche2k** [comment] 2015-05-20 11:29
Michal,

   As Calle, who has re-worked on the backend is not here, i think you are
the only one capable to fix the problem.

   For the Continuous Integration, if i understand correctly we have to
wait until we have the new server ready. Correct me if i am wrong.

Sandoche.

**Comment by pawal** [comment] 2015-05-20 11:38
On 20 May 2015, at 13:29, sandoche2k <notifications@github.com> wrote:

> Michal,
> 
> As Calle, who has re-worked on the backend is not here, i think you are
> the only one capable to fix the problem.
> 
> For the Continuous Integration, if i understand correctly we have to
> wait until we have the new server ready. Correct me if i am wrong.

As we have already discussed, Continuous Integration is testing the code (in this case “make test”) by using Travis CI. It has already been done for the Engine and the CLI.

You are talking about Continuous Deployment where code gets automatically tested on its way to production servers?

**Comment by sandoche2k** [comment] 2015-05-20 11:51
Yes you are right.

I meant Continuous integration + Continuous Deployment.

Sandoche.

**Comment by cdybedahl** [comment] 2015-06-01 06:28
I tried to warn before I left that the PostgreSQL backend code was not tested enough to be put into production, but it seems I did not do so loudly enough. The problem is that the code makes assumptions about the lifetime and stability of database connections that it can get away with for short periods of time, but not in a longer run. I'll be working on it this week.

**Comment by sandoche2k** [comment] 2015-06-04 06:09
@einar did you get errors after running for a period of time?

**Comment by einar** [comment] 2015-06-04 07:52
Sofar no "crashes" but it does run a LOT slower than it should for some reason (it should have 20K+ tests but it only has 2000+), I dont have time to investigate properly right now... I can let it keep running and look at it asap when I get time to do so but it might not be until monday. We did find a bug though and that's you cant seem to send more exactly 19 domains to the backend before it reports "Unknown error"... Will report more later.

**Comment by sandoche2k** [comment] 2015-06-04 08:35
@michal thanks for providing me the status on the production environment. What problems are you facing?

**Comment by mtoma** [comment] 2015-06-04 10:25
The status is that the production environment runs the backend test executing part from crontab as it was before. I updated those scripts to run with the new naming conventions of the backend.

The problem with zm_wb_daemon is 100% reproducible in the production environment as well as on my own machine with a different perl, os and PostgreSQL version.

It comes from the sharing of database connection from different forked processes. This is a very common problem with the perl DBI module and needs to be handled very carefully. It is one of the reasons why the crontab approach was preferred at first as it delegates all multitasking issues to the operating system instead of in-application fork()s.

I have a simple patch for this issue if needed but it must be validated that this patch does not exhaust database resources under heavy load.

**Comment by sandoche2k** [comment] 2015-06-04 11:48
So.. as now you have the patch and you have integrated the changes (except the start-up daemon), can we close this issue?

**Comment by pawal** [comment] 2015-06-04 11:56
It would be nice to have any changes in the current production code integrated into the code that is here in Github.

**Comment by einar** [comment] 2015-06-04 12:18
Still running Calles patch on a test machine but I have encountered 2 probable bugs in the backend so testing is not so fast... One is that you cant seem to send more than exactly 18 domains to the backend before it croaks with "Unknown error". The other issue is that an existing domain but one that is broken, like for example "21.se", can simply not be ran at all as preflight in Zonemaster is broken.

...and since the API is not properly documented I cant use that either. Testing this is HARD... ;(

**Comment by cdybedahl** [comment] 2015-06-04 12:26
The "Unknown error" is also from the preflight code. It  means that the DNS query made by the preflight test got a response with an RCODE that was not one of NOERROR or NXDOMAIN. Why on Earth it does that on the 19th request I have no idea (resource limit in the backend, maybe?).

**Comment by einar** [comment] 2015-06-04 13:33
If we (Michal) cant fix the preflight can we please remove it altogether? Currently it's making sure we cant test broken domains and there also seems to be some kind of query limit with it.

Yes, I wanted this. But I wanted something that works and I'm not really sure I wanted it in the backend either but whatever. ;P

Could this be changed to issue a query for the given domains' SOA with a 1 second timeout and if ANYTHING other than a NXDOMAIN is received within 1 second (SERVFAIL is OK, timeout is OK, crash is OK); do test? Or simply remove it, whatever is easiest to do.

**Comment by cdybedahl** [comment] 2015-06-04 13:36
I expressed my opinion on the preflight test earlier today in this comment: https://github.com/dotse/zonemaster/issues/370#issuecomment-108751157.

**Comment by mtoma** [comment] 2015-06-04 14:08
I have some difficulties following you here guys.
Einar can you explain more in detail your setup to reproduce this "18 domains limit" thing?

**Comment by sandoche2k** [comment] 2015-06-04 15:10
The most contentious problems that i see currently are :

1. Preflight test.
2. The backend breaks on a 18 domain limit.

For the preflight test there is a suggestion by Calle : dotse/zonemaster#370
(comment)
<https://github.com/dotse/zonemaster/issues/370#issuecomment-108751157>.
@mtoma Can we implement that? Your views? I think if this issue is solved,
we can close number of issues.

**Comment by mtoma** [comment] 2015-06-04 15:28
Not exactly sure what is the problem with preflight test.
21.se can be tested without problems using the "undelegated test tab"
https://www.zonemaster.net/test/14990

**Comment by sandoche2k** [comment] 2015-06-04 15:41
The difference i see is for 21.se

DNScheck :
http://dnscheck.iis.se/?time=1433431948&id=4983996&view=basic&test=standard
(on normal test and not undelegated test)
Zonemaster : For the same domain, we get a pop up "unknown error" (on
normal test and not undelegated test)

Similar results for similar cases (for e.g. gouv.fr)

So, the issue from my point of view is that, the pre-flight check triggers
only when the input field is a domain name which is invalid. For all other
conditions, you give to the engine for evaluation, so that the user knows
the real issue.

Feel free to disagree.

Sandoche.

**Comment by mtoma** [comment] 2015-06-04 16:45
What happens with 21.se in the "simple test tab" is that the preflight check returns SERVFAIL.
The preflight check then follows Stéphane's suggestion described in: 
https://github.com/dotse/zonemaster-gui/issues/86
Which states in case of SERVFAIL "something wrong happened" what is translated to "Unknown error while checking for domain existance"

**Comment by einar** [comment] 2015-06-05 07:41
Stephane calls this a bug, it shouldnt say either "Domain does not exist" nor "Unknown error"; it should test the domain with Zonemaster and let the tool identify the problem. Not sure what you mean when you say you have fixed it? Unknown error is not in any way better than "does not exist".

If you can not agree on how to run preflight (using mine or Calles instructions) could you please remove it instead? I want to be able to test broken domains with Zonemaster... ;P

**Comment by sandoche2k** [comment] 2015-06-08 13:02
@mtoma works for debian and ubuntu. Can you check for RHEL and if there is an issue update the error report.

**Comment by mtoma** [comment] 2015-06-08 13:04
Where is the fix for this issue?

----- Original Message -----

**Comment by sandoche2k** [comment] 2015-06-08 13:33
Following the installation instructions .. it works for me in Ubuntu and Debian. 

I am not able to reproduce the error that you have.

**Comment by mtoma** [comment] 2015-06-08 13:54
Well I told you that I reproduced this error in 2 different installations with two different OS versions and two different PostgreSQL versions.
I suggested a more or less acceptable quick fix for this that works for me but needs to be tested. I did not get an answer I think.
I don't really see what would be the purpose of testing the software again without a fix of this problem, am I missing something here?

----- Original Message -----

**Comment by sandoche2k** [comment] 2015-06-08 14:09
My test machines 

1. Debian 7 (wheezy), PostgreSQL 9.4.3, DBD 2.19.2, DBI 1.622
2. Ubuntu 14.0.4 TLS, PostgreSQL 9.3.7, DBD 3.5.1, DBI 1.63

Can you tell which are the one's you are using, so that i can try and reproduce the error.

**Comment by mtoma** [comment] 2015-06-08 14:28
No need to try to reproduce the error.
Calle's patch is what has to be done to fix this.
I just merged the pull request.

----- Original Message -----

**Comment by sandoche2k** [comment] 2015-06-08 14:29
Cool.. Thanks..

Can you confirm, in that case the issue could be closed ?

**Closed** 2015-06-09 16:29 UTC
Labels: bug, Prio High
