### ISSUE TITLE
Create a new index for get_test_history API

### ISSUE THREAD

**Issue by mtoma** [dotse/zonemaster-backend#292] opened 2017-06-29 08:39 UTC
CREATE INDEX test_results__domain_undelegated ON test_results (domain, undelegated)

Special care must be taken to create this index for the PostgreSQL backend as both fields are part of a JSON column.

**Comment by matsduf** [comment] 2017-12-19 13:51
@mtoma, can you explain what the problem is that you try to solve with the index?

**Comment by sandoche2k** [comment] 2018-01-03 10:04
@matsduf, @mattias-p Please check this new commit

**Comment by matsduf** [comment] 2018-01-11 17:23
Fixed by #324

**Closed by matsduf** 2018-01-11 17:23 UTC
