### ISSUE TITLE
Not able to install the backend(tar.gz) file using cpan

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster-backend#243] opened 2016-12-07 10:25 UTC
I followed the process 
```
perl Makefile.PL
make all
make manifest
make dist
```
And then the below. This method worked for the engine and the CLI. But not for the backend. 

```
sudo cpan -i Zonemaster-WebBackend-1.0.7.tar.gz
Loading internal null logger. Install Log::Log4perl for logging messages
CPAN: Storable loaded ok (v2.53_01)
Reading '/home/sandoche/.cpan/Metadata'
  Database was generated on Tue, 06 Dec 2016 16:29:02 GMT
Warning: Cannot install Zonemaster-WebBackend-1.0.7.tar.gz, don't know what it is.
Try the command

    i /Zonemaster-WebBackend-1.0.7.tar.gz/

to find objects with matching identifiers.
CPAN: Time::HiRes loaded ok (v1.9726)
sandoche@vps323914:~/zonemaster-backend$ sudo cpan -i /Zonemaster-WebBackend-1.0.7.tar.gz/
Loading internal null logger. Install Log::Log4perl for logging messages
CPAN: Storable loaded ok (v2.53_01)
Reading '/home/sandoche/.cpan/Metadata'
  Database was generated on Tue, 06 Dec 2016 16:29:02 GMT
Warning: Cannot install /Zonemaster-WebBackend-1.0.7.tar.gz/, don't know what it is.
Try the command

    i //Zonemaster-WebBackend-1.0.7.tar.gz//

to find objects with matching identifiers.
CPAN: Time::HiRes loaded ok (v1.9726)
```

**Comment by matsduf** [comment] 2016-12-07 10:45
CPAN installation is for packets on CPAN, not for our tarballs. For our tarballs, it is probably "make install".

**Comment by sandoche2k** [comment] 2016-12-07 10:50
Then why did it work for "engine" and "cli"?

**Comment by mattias-p** [comment] 2016-12-07 13:25
@matsduf We shouldn't be using `make install` here. The point is to install the actual preliminary distribution tarball for testing before it can be uploaded to CPAN.

@sandoche2k When I apply the above method to install tarballs for either *Engine* or *CLI*, they both fails in the same manner as described above. Do you have a record the exact commands you used when you succeeded with this, or can you reproduce any of them?

**Comment by sandoche2k** [comment] 2016-12-07 13:41
git clone repository

perl Makefile.PL
make all
make manifest
make dist

You will see a .tar.gz file created

sudo cpan -i /name of the tar.gze above file created/

**Comment by sandoche2k** [comment] 2016-12-07 13:44
@mattias-p 
```
sudo cpan -i /Zonemaster-v1.0.15.tar.gz/
[sudo] password for sandoche:
Reading '/root/.cpan/Metadata'
  Database was generated on Mon, 05 Dec 2016 23:17:02 GMT
Running make for Z/ZN/ZNMSTR/Zonemaster-v1.0.15.tar.gz
Checksum for /root/.cpan/sources/authors/id/Z/ZN/ZNMSTR/Zonemaster-v1.0.15.tar.gz ok

  CPAN.pm: Building Z/ZN/ZNMSTR/Zonemaster-v1.0.15.tar.gz

Checking if your kit is complete...
Looks good
Writing Makefile for Zonemaster
Writing MYMETA.yml and MYMETA.json
...
...

**Comment by mattias-p** [comment] 2016-12-07 13:45
@sandoche2k I think I've figured it out! When you installed *Engine* and *CLI* using `cpan`, I believe it didn't use the tarball in your working directory, but a cached tarball with the same name that had been previously downloaded from CPAN. The reason it worked for *Engine* and *CLI* is that those were released using the original version number while *Backend* (and *GUI*) were released with letter suffixes to their version numbers (`1.0.7-A` and `1.0.7-B` respectively), so you don't have any cached files with those names.

If you try bumping the version number before building the tarballs for *Engine* and *CLI* you'll see that `cpan` fails for those too in the same manner as described at the top.

**Comment by sandoche2k** [comment] 2016-12-07 13:50
That is not possible .. since every time i am doing a clean install.

**Comment by mattias-p** [comment] 2016-12-07 13:55
@sandoche2k Now that's interesting. How does *GUI* behave in this respect? And how do *Engine* and *CLI* behave if you bump their version numbers so they don't correspond to anything uploaded on CPAN?

**Comment by sandoche2k** [comment] 2016-12-07 14:02
:-)... i have not entered into installation of the GUI. Well let me try.

**Comment by mattias-p** [comment] 2016-12-07 14:16
@sandoche2k I have two more ideas to try:
* Run the `cpan -i` command without actually providing the tarball in the current directory.
* Remove your `~/.cpan` directory before running `sudo cpan -i /Zonemaster-v1.0.15.tar.gz/` and watch the output to see whether it says it downloads the tarball from CPAN rather than using the one with the same name in your current working directory.

**Comment by sandoche2k** [comment] 2016-12-07 14:38
I did the same manner as you indicated.

rm -rf /home/sandoche/.cpan
rm -rf /home/sandoche/.cpanm

sudo cpan -i /Zonemaster-v1.0.15.tar.gz/

It works...

I will check with CLI and backend.. In case if you can do a clean install
... can you check also?

**Comment by mattias-p** [comment] 2016-12-07 14:47
When I run this command:
```sh
$ sudo rm -rf ~/.cpan && sudo cpan -i /Zonemaster-v1.0.15.tar.gz/
```
Somewhere in the middle of the output I get these very suspicious lines:
```
Running make for Z/ZN/ZNMSTR/Zonemaster-v1.0.15.tar.gz
Fetching with LWP:
http://ftp.nluug.nl/languages/perl/CPAN/authors/id/Z/ZN/ZNMSTR/Zonemaster-v1.0.15.tar.gz
Fetching with LWP:
http://ftp.nluug.nl/languages/perl/CPAN/authors/id/Z/ZN/ZNMSTR/CHECKSUMS
Checksum for /home/mattiasp/.cpan/sources/authors/id/Z/ZN/ZNMSTR/Zonemaster-v1.0.15.tar.gz ok
Uncompressed /home/mattiasp/.cpan/sources/authors/id/Z/ZN/ZNMSTR/Zonemaster-v1.0.15.tar.gz successfully
```
This is regardless of whether I've got a `Zonemaster-v1.0.15.tar.gz`-file in my current working directory.

**Comment by matsduf** [comment] 2016-12-07 15:15
> When i rename the file with a different version to `Zonemaster-CLI-v1.0.6.tar.gz`and ran the command `sudo cpan -i /Zonemaster-CLI-v1.0.6.tar.gz` it did not work.

Did you also update the version in Zonemaster::CLI.pm? I think those must match.

**Comment by sandoche2k** [comment] 2016-12-07 15:19
Same issue even after changing the version number in CLI.pm

**Comment by mtoma** [comment] 2016-12-07 16:21
Not sure about what cpanm can do but for me the way to install a package like CPAN would have done it is to:
- download the tarball
- uncompress into a folder
- run perl Makefile.PL
- run make
- run sudo make install

----- Original Message -----

**Comment by sandoche2k** [comment] 2016-12-08 07:34
@mtoma you are right. It has to be done using make. I do not think that you can install a local file using cpan.

**Closed** 2016-12-08 09:51 UTC
