### ISSUE TITLE
sudo cpan -i Zonemaster::Backend fails in Debian 

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster-backend#313] opened 2017-11-03 07:38 UTC
```sh 
Running make test
PERL_DL_NONLAZY=1 PERL_USE_UNSAFE_INC=1 /usr/bin/perl "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'inc', 'blib/lib', 'blib/arch')" t/*.t
t/test01.t ................ ok    
t/test_validate_syntax.t .. 1/? 
#   Failed test 'idn domain=[é]'
#   at t/test_validate_syntax.t line 34.
# Domain name contains non-ascii characters and IDN conversion is not installed

#   Failed test 'idn domain=[éé]'
#   at t/test_validate_syntax.t line 39.
# Domain name contains non-ascii characters and IDN conversion is not installed

#   Failed test 'idn domain=[é]'
#   at t/test_validate_syntax.t line 88.
# NS [&eacute;] contains non-ascii characters and IDN conversion is not installed

#   Failed test 'idn domain=[éé]'
#   at t/test_validate_syntax.t line 93.
# NS [&eacute;&eacute;] contains non-ascii characters and IDN conversion is not installed
# Looks like you failed 4 tests of 27.
t/test_validate_syntax.t .. Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/27 subtests 

Test Summary Report
-------------------
t/test_validate_syntax.t (Wstat: 1024 Tests: 27 Failed: 4)
  Failed tests:  4-5, 12-13
  Non-zero exit status: 4
Files=2, Tests=54, 10 wallclock secs ( 0.03 usr  0.00 sys +  8.00 cusr  0.27 csys =  8.30 CPU)
Result: FAIL
Failed 1/2 test programs. 4/54 subtests failed.
Makefile:795: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 4
  ZNMSTR/Zonemaster-Backend-2.0.0.tar.gz
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports ZNMSTR/Zonemaster-Backend-2.0.0.tar.gz
```

**Comment by mattias-p** [comment] 2017-11-03 11:15
Duplicate of #235.

**Closed by mattias-p** 2017-11-03 11:15 UTC
